#+STARTUP: beamer 
#+LATEX_CLASS: beamer
#+BEAMER_THEME: Montpellier
#+OPTIONS: H:2 toc:nil
#+toc: nil
#+TITLE: The Longshot bias in market data: Evidence from Counter-Strike: Global Offensive
#+AUTHOR: Timothy Schwieg
#+LATEX_HEADER: \usepackage{tabularx,ragged2e,booktabs,caption}
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)


* Topic
** Loot Boxes

- Many video games have chosen to sell cosmetic alterations to their
  games using randomization mechanisms called ``loot boxes''
- Economic Literature tells us that there is no benefit to
  randomization for risk-neutral consumers, so the benefit must come
  from risk-loving consumers.
- What aspect of these lotteries is generating the revenue for the
  companies selling them?
- How much more revenue-generating is this compared to traditional
  selling mechanisms?

** Why do we care?
- We are interested in discovering what drives this market to feature
  randomization mechanisms.
- Are consumers inherently more risk-loving when they play video
  games?
- Is this driven by consumers over-weighting tiny probabilities as
  cumulative prospect theory suggests?
- Are consumers weighing benefits and losses differently?
- What is the magnitude of these gains from randomization?

* Data
** The Data
- Contains complete market history for all items sold in the Steam
  Community Market for /Counter-Strike: Global Offensive/
- Market history is specific to the hour for the last 30 days,
  specific to the day for the remaining time the item has existed.
- Contains all active buy and sell orders for each of these items as
  of March 31^st 2018.
- Number of active players per day and unique twitch viewers per day


** Pictures
[[../Plots/BreakEvenScatter.pdf]]

** Does Size Matter?

[[../Plots/LossesVSize.pdf]]

** Lotteries

#+BEGIN_EXPORT latex
\begin{minipage}{\linewidth}
  \centering
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{@{}lcccccccc@{}}\toprule
    & \multicolumn{2}{c}{Values} & &\multicolumn{5}{c}{Number of Contents}\\
    \cmidrule{2-3} \cmidrule{5-9}
  Case & $\mathbb{E}[V]$ & Price &\quad& \#Blue & \#Purple & \#Pink & \#Red & \#Gold\\\midrule
Operation Wildfire  & 0.89891 & 2.5307 &\quad& 26 & 18 & 14 & 9 & 50\\
Operation Breakout  & 0.77011 & 2.5305 &\quad& 24 & 15 & 12 & 10 & 56\\
Falchion Case  & 0.95072 & 2.5323 &\quad& 27 & 24 & 11 & 9 & 59\\
Shadow Case  & 0.85299 & 2.5349 &\quad& 29 & 17 & 14 & 10 & 59\\
Huntsman Weapon Case  & 0.95531 & 3.3181 &\quad& 25 & 17 & 12 & 8 & 62\\
Spectrum Case  & 0.98146 & 2.53 &\quad& 34 & 23 & 15 & 9 & 68\\
Chroma 2 Case  & 1.0058 & 2.53 &\quad& 25 & 13 & 13 & 9 & 81\\
Chroma 3 Case  & 0.66099 & 2.53 &\quad& 30 & 19 & 11 & 10 & 81\\
Chroma Case  & 0.83215 & 2.55 &\quad& 23 & 20 & 10 & 4 & 81\\
Glove Case  & 0.84301 & 2.53 &\quad& 27 & 26 & 9 & 12 & 89\\
Operation Hydra  & 1.5465 & 4.0827 &\quad& 25 & 20 & 14 & 9 & 89\\
Gamma 2 Case  & 0.68335 & 2.53 &\quad& 31 & 22 & 13 & 7 & 128\\
Gamma Case & 0.80717 & 2.53 &\quad& 31 & 21 & 11 & 10 & 128\\\bottomrule
  \end{tabular}%
}
  
\end{minipage}

#+END_EXPORT


** High  Content Lotteries
#+BEGIN_EXPORT latex
\begin{minipage}{\linewidth}
  \centering
  \resizebox{\columnwidth}{!}{%
  \begin{tabular}{@{}lcccccccc@{}}\toprule
    & \multicolumn{2}{c}{Values} & &\multicolumn{5}{c}{Number of Contents}\\
    \cmidrule{2-3} \cmidrule{5-9}
  Case & $\mathbb{E}[V]$ & Price &\quad& \#Blue & \#Purple & \#Pink & \#Red & \#Gold\\\midrule
CS:GO Weapon  & 4.4611 & 9.3248 &\quad& 7 & 6 & 7 & 2 & 228\\
eSports 2013 Case  & 3.2708 & 10.354 &\quad& 8 & 13 & 7 & 2 & 228\\
eSports 2013 Winter  & 1.5687 & 2.6441 &\quad& 18 & 9 & 11 & 3 & 228\\
eSports 2014 Summer  & 1.4136 & 2.7414 &\quad& 21 & 19 & 16 & 9 & 228\\
Operation Bravo  & 4.3567 & 12.628 &\quad& 26 & 15 & 9 & 6 & 228\\
Operation Phoenix  & 0.85507 & 2.5416 &\quad& 15 & 12 & 9 & 7 & 228\\
Operation Vanguard  & 1.038 & 2.5928 &\quad& 17 & 13 & 12 & 10 & 228\\
Revolver Case  & 1.1045 & 2.53 &\quad& 24 & 25 & 12 & 9 & 228\\
Winter Offensive  & 1.299 & 3.5079 &\quad& 14 & 14 & 12 & 6 & 228\\\bottomrule
  \end{tabular}%
}
  
\end{minipage}

#+END_EXPORT
* Model

** Discrete Choice - Berry (1994)

Utility for these lotteries is quasi-linear
\begin{equation*}
  u_{ijt} = V( x_{jt}, p_{jt}; \theta ) + \xi_{jt} + \epsilon_{ij} \quad \epsilon_{ij} \sim Gumbel
\end{equation*}

Consumers choose the lottery that has the highest utility for them: 

\begin{equation*}
  \Pr( i \rightarrow j ) = \frac{\exp( V(x_{jt},p_{jt} ; \theta) + \xi_{jt})}{ \sum_{k \in \mathcal{F}}
    \exp(V(x_{jt},p_{jt}; \theta) + \xi_{kt})}
\end{equation*}

Using an outside option that is normalized so that it has zero
utility:

\begin{equation*}
  \log s_{jt} - \log s_{0t} = V(x_{jt}, p_{jt}; \theta) + \xi_{jt}
\end{equation*}

** Implications
- Differentiated Goods
- Prediction based on market shares
- Homogeneous Consumers - Is this reasonable?
- No structure placed on $\xi$



** Cumulative Prospect Theory
- Four main components: Reference dependence, loss aversion,
  diminishing sensitivity, and probability weighting

- Diminishing sensitivity and loss aversion are summarized by the
  valuation function for each content of the lottery. 
- $x$ is not the content of the lottery, but the value of the gain or
  loss of that content relative to some reference point.
#+BEGIN_EXPORT latex
\begin{align*}
  v(x) &=
  \begin{cases}
    x^\alpha \quad &x \geq 0\\
    -\lambda(-x)^\alpha \quad &x < 0
  \end{cases}\\
\end{align*}
#+END_EXPORT

** Reference dependence and Loss Aversion
- What is the proper reference point?
- Can it be estimated?
- How is loss aversion tied to the reference point?
 
#+BEGIN_EXPORT latex
\begin{center}
\includegraphics[width=.75\linewidth]{../Plots/ValueFunction.pdf}
\end{center}
#+END_EXPORT

** Probability Weighting Function
#+BEGIN_EXPORT latex
\begin{equation*}
  w(p) = \frac{\gamma p^{\delta}}{\gamma p^{\delta} + (1-p)^{\delta}}
\end{equation*}

\begin{center}
\includegraphics[width=.75\linewidth]{../Plots/WeightFun.pdf}
\end{center}
#+END_EXPORT


** Valuation of a Lottery
- We compute the "as-if" probability taking differences of the
  weighted-CDF function.
#+BEGIN_EXPORT latex
\begin{align*}
  \Pi_{s_i} &= \sum_{j=1}^{s_i} \pi_{s_j}\\
  p_i &= w( \Pi_{s_i}) - w(\Pi_{s_{i-1}})\\
  F(x_i) &= \left[  w( \Pi_{s_i}) - w(\Pi_{s_i - 1}) \right] v( x_i - R)\\
  \\
  V &= \sum_{i=1} F(x_i)\\            
\end{align*}
#+END_EXPORT
* Estimation
** Constant Term
- To normalize the utility to an outside good, need a constant term
- There is no interpretation for this constant term.
- Combines mis-specification of outside good, expected value of $\xi$
  and the normalizing utility of the outside good. 

** Estimation
- Price is determined by intersection of supply and demand and is
  therefore endogenous
- Instrument with the changes in daily player base from the average
  number of players

\begin{align*}
  \xi_{jt} = \log s_{jt} - \log s_{0t} - \beta - V( x_{jt}, p_{jt}; \theta)
\end{align*}
Using the orthogonality of $\xi_{jt}$ to the instruments and exogenous
parameters:
\begin{align*}
  &\min_{\bm{\xi}_{j,t}, \xi_{j,t}} \sum_{j,t}\bm{\xi}_{j,t}' \Omega \bm{\xi}_{j,t}\\
  \text{subject to: } &\xi_{j,t} = \log s_{jt} - \log s_{0t} - \beta - V( x_{jt}, p_{jt}; \theta)\\
  &\bm{\xi}_{j,t} = \xi_{j,t} \bm{Z}_{j,t}  
\end{align*}

** Computation
- Estimated using KNITRO
- RMSE is computed both in sample and for an out-of-sample test to
  determine over-fitting
- $\bar{R}^2$ is computed as $1 - \frac{\mathbb{V}(\xi)}{\mathbb{V}(Y)}$
- J-Statistic  Critical Values:
-- Fixed Effects: 5% 314.6784, 1% 332.4796


-- No Fixed Effects: 5% 337.1254, 1% 355.5251
* Results

** Results

#+BEGIN_EXPORT latex
\begin{minipage}{\linewidth}
  \centering
  \scalebox{0.55}{%
\begin{tabular}{@{}cccccc@{}}\toprule
  \multicolumn{3}{c}{$\exV{V}$ + Price Reference Point} & &\\
\cmidrule{1-3}
$\alpha$ & 0.56534 (2.03484) & $\lambda$ & 1.36844 (10.8477)\\
$\gamma$ & 1.0 (6.36280) & $\delta$ & 1.0 (9.47887)\\
  In Sample RMSE & 1.23649 & Out Sample RMSE & 1.4337\\
  $\bar{R}^2$ & 0.18880 & J-Statistic & 825.185\\
  \midrule
 \multicolumn{3}{c}{$\exV{V}$ + Price Reference Point and Fixed
  Effects} & &\\
\cmidrule{1-3}
$\alpha$ & 0.79549 (4.6084) & $\lambda$ & 0.60091 (9.85376)\\
$\gamma$ & 1.0 (9.79014) & $\delta$ & 1.0 (21.5814)\\
  In Sample RMSE & 1.08121 & Out Sample RMSE & 1.10642\\
  $\bar{R}^2$ & 0.51688 & J-Statistic & 558.41\\
  \midrule
\multicolumn{3}{c}{Price Reference Point} & &\\
\cmidrule{1-3}
$\alpha$ & 0.47457 (5.4068) & $\lambda$ & 0.54667 (14.56967)\\
$\gamma$ & 1.0 (10.97014) & $\delta$ & 1.0 (10.85583)\\
  In Sample RMSE & 1.52584 & Out Sample RMSE & 1.5258\\
  $\bar{R}^2$ & 0.08117 & J-Statistic & 860.261\\
  \midrule
\multicolumn{3}{c}{Price Reference Point and Fixed Effects} & &\\
\cmidrule{1-3}
$\alpha$ & 0.8215 (7.6682) & $\lambda$ & 0.3152 (7.3252)\\
$\gamma$ & 1.0 (7.6753) & $\delta$ & 1.0 (15.7306)\\
  In Sample RMSE & 1.01432 & Out Sample RMSE & 1.07900\\
  $\bar{R}^2$ & 0.54053 & J-Statistic & 351.73\\
  \midrule
\multicolumn{3}{c}{Rational - CRRA} & &\\
\cmidrule{1-3}
$\alpha$ & 0.17411 ( 6093.657) & $\beta$ & -0.32488 (0.28937)\\
  In Sample RMSE & 0.98513 & Out Sample RMSE & 1.10097\\
  $\bar{R}^2$ & 0.52163 & J-Statistic & 570.394\\\bottomrule
\end{tabular}
}
\end{minipage}
#+END_EXPORT

** What stories does this tell?
- Rational CRRA story is one of risk aversion
- Poor fit without fixed effects means that individuals may not be
  sensitive to price changes
- Cumulative Prospect Models do not tell a story of probability
  weighting. 
- Low fit means that there is more driving this effect than a single
  representative agent

** Where to go from here?
- Belief Heterogeneity
- Preference Heterogeneity
- Non-parametric fit
- Explore other alternatives for views of price
- Larger amount of data used
